name: Build BarkWatch APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install dependencies
        run: sudo apt-get install -y unzip wget curl

      - name: Set Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: barkwatch-apk
          path: app/build/outputs/apk/debug/app-debug.apk